### PR TITLE
Fix subscription purchase

### LINKED ISSUE #297: Subscription purchase fails due to gass limit error
When trying to buy a subscription from the website, after approving the token amount to spend and providing the signature, the purchase flow fails on the buy step with the following error:

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #297.

### CODE REVIEW

File: src/utils/contracts/Predictoor.ts [hunk 1]
```diff
@@ -173,28 +172,28 @@ class Predictoor {
...
       }
       // Get gas price and limit
-      //const gasPrice = await this.provider.getGasPrice()
-      //let gasLimit = await this.instance
-      //  .connect(user)
-      //  .estimateGas.buyFromFreAndOrder(orderParams, freParams)
+      const gasPrice = await this.provider.getGasPrice()
+      let gasLimit = await this.instanceWrite
+        .connect(user)
+        .estimateGas.buyFromFreAndOrder(orderParams, freParams)
```
Comment (idiom-bytes) [inline src/utils/contracts/Predictoor.ts:178]: Good work.

**Review by idiom-bytes — APPROVED** [review]
Approved. Code is now using contract fn to estimate gas cost.
